// GET Categories
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY_DETAIL = "GET_CATEGORY_DETAIL";
export const GET_CATEGORIES_EVENTS = "GET_CATEGORIES_EVENTS";
export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENTS_TODAY = "GET_EVENTS_TODAY";
export const GET_UPCOMING_EVENTS = "GET_UPCOMING_EVENT";
export const GET_EVENTS_DETAIL = "GET_EVENTS_DETAIL";
export const GET_EVENTS_SEARCH = "GET_EVENTS_SEARCH";
export const SIGNUP = "SIGNUP";
export const SIGN = "SIGN";
export const USER_DETAIL = "USER_DETAIL";
export const USER_EVENTS_FAVORITES = "USER_EVENTS_FAVORITES";
export const USER_SET_LIKE_EVENT = "USER_SET_LIKE_EVENT";
export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";
